import React from "react";
const HomePage = () => {
  return <div>
      <h1>Welcome To INKiusitor Admin</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper risus in hendrerit gravida. Sed libero enim sed faucibus turpis in. Non pulvinar neque laoreet suspendisse interdum consectetur. Ut tellus elementum sagittis vitae et leo duis. Nulla at volutpat diam ut venenatis tellus in metus. Metus vulputate eu scelerisque felis. Consequat id porta nibh venenatis cras sed felis. Ut tellus elementum sagittis vitae et leo duis. Arcu non sodales neque sodales ut etiam sit amet. Nunc sed id semper risus in hendrerit gravida rutrum quisque. Dolor sit amet consectetur adipiscing elit. Adipiscing vitae proin sagittis nisl rhoncus. Metus vulputate eu scelerisque felis imperdiet proin fermentum leo vel. Neque laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt.

Sollicitudin nibh sit amet commodo nulla. Sem fringilla ut morbi tincidunt augue interdum. Risus commodo viverra maecenas accumsan. Arcu risus quis varius quam quisque. Convallis posuere morbi leo urna molestie at elementum eu. Vel facilisis volutpat est velit. Tincidunt id aliquet risus feugiat in ante metus. Libero nunc consequat interdum varius. Mi proin sed libero enim sed faucibus. Pulvinar elementum integer enim neque volutpat ac. Sit amet porttitor eget dolor morbi. Pharetra magna ac placerat vestibulum lectus mauris. Integer eget aliquet nibh praesent tristique magna sit. Velit aliquet sagittis id consectetur purus ut. Molestie ac feugiat sed lectus. Scelerisque varius morbi enim nunc faucibus. Arcu non sodales neque sodales ut etiam. Egestas diam in arcu cursus euismod. Cursus in hac habitasse platea dictumst quisque.

Odio eu feugiat pretium nibh ipsum consequat nisl. Libero id faucibus nisl tincidunt eget nullam non nisi. Dolor magna eget est lorem ipsum dolor sit amet. Ipsum dolor sit amet consectetur. Volutpat consequat mauris nunc congue nisi vitae suscipit tellus. Molestie a iaculis at erat pellentesque. Viverra suspendisse potenti nullam ac tortor vitae purus. Facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum dui. Tempor orci dapibus ultrices in iaculis nunc sed. Dui accumsan sit amet nulla facilisi morbi tempus iaculis. In egestas erat imperdiet sed euismod nisi porta lorem mollis. Feugiat pretium nibh ipsum consequat nisl vel pretium lectus. Mauris pharetra et ultrices neque. Porta non pulvinar neque laoreet suspendisse interdum consectetur. Aliquam sem et tortor consequat id porta nibh. Est ante in nibh mauris cursus mattis molestie a.

Eget aliquet nibh praesent tristique magna sit. Neque convallis a cras semper auctor neque vitae. Proin sagittis nisl rhoncus mattis rhoncus urna neque viverra. Duis ultricies lacus sed turpis. Sollicitudin ac orci phasellus egestas tellus. Laoreet sit amet cursus sit amet dictum sit. Massa vitae tortor condimentum lacinia. Tellus integer feugiat scelerisque varius. At elementum eu facilisis sed odio morbi. Sed nisi lacus sed viverra. Lorem ipsum dolor sit amet consectetur adipiscing. Sit amet nulla facilisi morbi tempus iaculis urna id volutpat. Semper auctor neque vitae tempus quam. Nulla aliquet porttitor lacus luctus accumsan tortor. Ultricies leo integer malesuada nunc vel risus commodo. Nibh venenatis cras sed felis eget velit aliquet. Sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum. Luctus accumsan tortor posuere ac ut. Nam aliquam sem et tortor consequat id. Aliquet lectus proin nibh nisl condimentum id venenatis.

Nunc aliquet bibendum enim facilisis gravida neque convallis. Euismod nisi porta lorem mollis aliquam ut porttitor. Sed augue lacus viverra vitae congue eu consequat. Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. In pellentesque massa placerat duis ultricies lacus sed turpis tincidunt. Pharetra pharetra massa massa ultricies mi quis hendrerit dolor. Pharetra massa massa ultricies mi. Sit amet volutpat consequat mauris nunc congue. Lacinia at quis risus sed. Posuere ac ut consequat semper viverra nam. Tortor aliquam nulla facilisi cras fermentum. Suspendisse faucibus interdum posuere lorem ipsum dolor sit amet. Ipsum consequat nisl vel pretium lectus quam. Enim nulla aliquet porttitor lacus luctus accumsan tortor posuere ac. Condimentum lacinia quis vel eros donec ac odio. Habitant morbi tristique senectus et netus et malesuada. Amet nisl purus in mollis nunc sed.</p>
  </div>;
};
export default HomePage;
